-- restaurantsテーブル
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (1, 13, 'すし太郎', 'sushi-taro.jpg', '新鮮なネタと職人技が自慢の寿司店。', '1000円', '5000円', '460-0008', '愛知県名古屋市中区栄1-1-1', '11:30', '21:00', 30, '水曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (2, 20, '焼肉楽園', 'yakiniku-rakuen.jpg', '極上の焼肉と多彩なサイドメニューが楽しめる焼肉店。', '2000円', '8000円', '461-0001', '愛知県名古屋市東区東山1-2-3', '17:00', '23:00', 50, '月曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (3, 2, 'イタリアン美食屋', 'italian-bishokuya.jpg', '新鮮な地元食材を使用した本格イタリアンが味わえる。', '1500円', '6000円', '464-0003', '愛知県名古屋市西区本山2-3-4', '18:00', '22:30', 40, '日曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (4, 14, 'ラーメン一番星', 'ramen-ichiban.jpg', 'こだわりのスープと自家製麺が自慢のラーメン店。', '800円', '1500円', '461-0025', '愛知県名古屋市東区葵1-4-5', '11:00', '22:00', 25, '水曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (5, 1, '天ぷら天国', 'tenpura-tengoku.jpg', 'サクサクの天ぷらと香ばしいご飯が絶品。', '1200円', '3000円', '460-0011', '愛知県名古屋市中区大須3-2-1', '12:00', '20:30', 35, '日曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (6, 11, 'カフェ・ル・ブラン', 'cafe-le-blanc.jpg', '上質なコーヒーと美味しいスイーツが楽しめるカフェ。', '500円', '2000円', '464-0850', '愛知県名古屋市千種区今池2-1-3', '10:00', '18:00', 20, '月曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (7, 13, '寿司マスター', 'sushi-master.jpg', '贅沢な海の幸が楽しめる寿司専門店。', '1500円', '7000円', '461-0007', '愛知県名古屋市東区白壁1-5-2', '12:00', '22:30', 28, '日曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (8, 12, '焼き鳥横丁', 'yakitori-yokocho.jpg', '新鮮な鳥料理と種類豊富なお酒が楽しめる焼き鳥屋。', '1000円', '4500円', '460-0023', '愛知県名古屋市中区大須4-3-1', '18:00', '24:00', 40, '水曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (9, 4, '中華楼', 'chinese-rou.jpg', '本場の味を追求した本格中華料理店。', '1200円', '5000円', '464-0819', '愛知県名古屋市千種区今池3-2-1', '11:30', '21:30', 35, '第2、第4木曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (10, 19, '海鮮亭', 'kaisen-tei.jpg', '新鮮な海の幸が味わえる海鮮料理専門店。', '1800円', '7500円', '461-0021', '愛知県名古屋市東区東新町2-4-6', '17:00', '23:30', 32, '第2、第4木曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (11, 11, 'ベーカリーコーナー', 'bakery-corner.jpg', '焼きたてのパンと美味しいコーヒーが楽しめるベーカリーショップ。', '300円', '1200円', '460-0031', '愛知県名古屋市中区栄2-1-3', '7:00', '19:00', 15, '月曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (12, 1, '和風居酒屋 花火', 'wafu-izakaya-hanabi.jpg', '季節の素材を使った和風居酒屋。', '1000円', '4500円', '461-0015', '愛知県名古屋市東区大橋2-1-8', '18:00', '23:30', 28, '第2、第4木曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (13, 10, 'ベトナムキッチン ほっと', 'vietnamese-kitchen-hot.jpg', '本場ベトナムの味わいを楽しめるキッチン。', '800円', '2500円', '460-0024', '愛知県名古屋市中区錦3-4-7', '11:30', '21:00', 25, '水曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (14, 15, 'デリシャスバーガー', 'delicious-burger.jpg', 'ジューシーで美味しいハンバーガーが自慢の店。', '700円', '1800円', '464-0822', '愛知県名古屋市千種区今池4-1-2', '12:00', '20:30', 35, '日曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (15, 7, 'カレーの香り', 'curry-no-kaori.jpg', '香り高いスパイスが特徴の美味しいカレー専門店。', '900円', '2000円', '461-0037', '愛知県名古屋市東区矢田2-3-6', '11:00', '22:00', 30, '第2、第4木曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (16, 9, '韓国家庭料理 おばんざい', 'korean-home-cooking-obanzai.jpg', '本格的な韓国家庭料理が楽しめる。', '1500円', '5000円', '460-0001', '愛知県名古屋市中区丸の内3-2-4', '17:00', '23:00', 40, '水曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (17, 11, 'ジャズカフェ シンガーズ', 'jazz-cafe-singers.jpg', '生演奏のジャズと美味しいコーヒーが楽しめるカフェ。', '600円', '1800円', '464-0841', '愛知県名古屋市千種区今池1-2-8', '13:00', '22:00', 20, '月曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (18, 12, '串焼きや とり匠', 'kushiyaki-toritaku.jpg', '新鮮な鳥を使用した串焼きが自慢の店。', '1200円', '3500円', '461-0022', '愛知県名古屋市東区葵2-3-1', '18:30', '24:00', 30, '第2、第4木曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (19, 13, 'モダン寿司 一八寿司', 'modern-sushi-ichihasushi.jpg', 'モダンな雰囲気で楽しむ寿司の名店。', '2000円', '8000円', '460-0006', '愛知県名古屋市中区大須1-4-5', '12:00', '22:30', 25, '月曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (20, 3, 'タイムレスレストラン', 'timeless-restaurant.jpg', '時を忘れて楽しむ、多彩な料理が楽しめるレストラン。', '1500円', '6000円', '464-0843', '愛知県名古屋市千種区今池4-2-1', '11:30', '21:30', 35, '水曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (21, 11, '海辺のカフェ ブルーウェーブ', 'seaside-cafe-bluewave.jpg', '海を感じながら楽しむこだわりのカフェ。', '700円', '2500円', '461-0024', '愛知県名古屋市東区東大浜1-3-7', '10:00', '19:00', 28, '不定休');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (22, 11, 'ジャズカフェ シンガーズ', 'jazz-cafe-singers.jpg', '生演奏のジャズと美味しいコーヒーが楽しめるカフェ。', '600円', '1800円', '464-0841', '愛知県名古屋市千種区今池1-2-8', '13:00', '22:00', 20, '不定休');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (23, 12, '串焼きや とり匠', 'kushiyaki-toritaku.jpg', '新鮮な鳥を使用した串焼きが自慢の店。', '1200円', '3500円', '461-0022', '愛知県名古屋市東区葵2-3-1', '18:30', '24:00', 30, '第2、第4木曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (24, 3, 'タイムレスレストラン', 'timeless-restaurant.jpg', '時を忘れて楽しむ、多彩な料理が楽しめるレストラン。', '1500円', '6000円', '464-0843', '愛知県名古屋市千種区今池4-2-1', '11:30', '21:30', 35, '水曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (25, 1, '和風居酒屋 月の舞', 'wafu-izakaya-tsukinomai.jpg', '四季折々の日本の美味を楽しむ和風居酒屋。', '1000円', '4000円', '461-0018', '愛知県名古屋市東区星が丘2-4-6', '17:30', '23:00', 32, '第2、第4木曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (26, 17, 'ベジタリアンダイニング グリーンハーモニー', 'vegetarian-dining-green-harmony.jpg', '新鮮な野菜を使用したヘルシーな料理が楽しめる。', '800円', '2500円', '460-0027', '愛知県名古屋市中区東桜1-3-5', '11:00', '20:30', 28, '水曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (27, 3, 'フレンチビストロ ル・プチボヌール', 'french-bistro-le-petit-bonheur.jpg', 'フレンチビストロの名店で本格的なフランス料理を堪能。', '2500円', '10000円', '464-0855', '愛知県名古屋市千種区今池5-1-2', '18:00', '23:30', 40, '水曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (28, 17, 'オーガニックカフェ グリーンリーフ', 'organic-cafe-green-leaf.jpg', '新鮮なオーガニック食材を使用したカフェ。', '600円', '1800円', '461-0035', '愛知県名古屋市東区東桜3-2-7', '10:00', '19:00', 20, '第2、第4木曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (29, 1, 'とんかつ横丁 かつ福', 'tonkatsu-yokocho-katsufuku.jpg', 'ジューシーでサクサクのとんかつが楽しめる専門店。', '1200円', '4500円', '460-0017', '愛知県名古屋市中区大須5-1-3', '11:30', '21:00', 35, '第2、第4木曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (30, 14, 'モダンラーメン ブラックノードル', 'modern-ramen-black-noodle.jpg', 'シックな雰囲気のモダンラーメン専門店。', '900円', '2000円', '464-0022', '愛知県名古屋市西区名駅1-1-1', '11:00', '22:00', 30, '第2、第4木曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (31, 19, 'シーフードダイナー ブルーウェーブ', 'seafood-diner-bluewave.jpg', '新鮮なシーフードを使用したダイナー。', '1500円', '5000円', '461-0012', '愛知県名古屋市東区東大口1-2-4', '17:00', '23:00', 25, '第2、第4木曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (32, 11, 'モダンカフェ ブラウンビーンズ', 'modern-cafe-brown-beans.jpg', 'シンプルでモダンな雰囲気のカフェ。', '500円', '1800円', '464-0011', '愛知県名古屋市千種区東山2-3-7', '10:00', '18:00', 15, '不定休');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (33, 1, '和風割烹 さくら亭', 'wafu-kappo-sakuratei.jpg', '日本の伝統的な料理が楽しめる和風割烹。', '1800円', '7000円', '460-0016', '愛知県名古屋市中区栄3-1-8', '12:00', '22:30', 28, '不定休');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (34, 6, 'メキシカンタコス サルサ', 'mexican-tacos-salsa.jpg', 'アツアツのメキシカンタコスが楽しめる。', '1000円', '3500円', '461-0026', '愛知県名古屋市東区東桜4-2-1', '18:00', '24:00', 40, '不定休');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (35, 17, 'ベジタリアンカフェ フレッシュグリーン', 'vegetarian-cafe-fresh-green.jpg', '新鮮な野菜とオーガニックな食材を使用したベジタリアンカフェ。', '700円', '2500円', '460-0026', '愛知県名古屋市中区東桜2-4-5', '10:00', '19:00', 28, '不定休');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (36, 1, '焼き魚の店 うるめしや', 'grilled-fish-urumeshiya.jpg', '新鮮な魚を使った焼き魚が楽しめる専門店。', '1200円', '3500円', '461-0006', '愛知県名古屋市東区東桜5-1-3', '18:30', '24:00', 30, '月曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (37, 19, 'シーフードバー グリルマリン', 'seafood-bar-grill-marine.jpg', '新鮮なシーフードが楽しめるアメリカンスタイルのバー。', '1500円', '5000円', '464-0032', '愛知県名古屋市西区名古屋港1-1-10', '17:00', '23:00', 25, '月曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (38, 13, '寿司割烹 さかなや', 'sushi-kappo-sakanaya.jpg', '新鮮なネタが自慢の寿司割烹。', '1800円', '7000円', '460-0021', '愛知県名古屋市中区大須2-1-4', '12:00', '22:30', 28, '不定休');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (39, 14, 'ラーメン工房 一等星', 'ramen-kobo-ichitoosei.jpg', 'こだわりの麺とスープが自慢のラーメン工房。', '900円', '2000円', '464-0821', '愛知県名古屋市千種区今池6-2-3', '11:00', '22:00', 30, '不定休');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (40, 6, 'メキシカンビストロ サンタマリータ', 'mexican-bistro-santa-margarita.jpg', 'メキシコ料理が楽しめるアットホームなビストロ。', '1000円', '3500円', '461-0031', '愛知県名古屋市東区矢田1-3-5', '18:00', '24:00', 40, '不定休');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (41, 3, 'モダンフレンチ ル・プティサロン', 'modern-french-le-petit-salon.jpg', 'モダンで洗練されたフレンチが楽しめるレストラン。', '2500円', '10000円', '460-0012', '愛知県名古屋市中区栄4-1-2', '18:00', '23:30', 35, '不定休');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (42, 1, '和食バル うまいもんや', 'washoku-bar-umaimonya.jpg', '和食の逸品が楽しめるバル。', '1200円', '4500円', '461-0024', '愛知県名古屋市東区東大和田3-2-7', '11:30', '21:00', 35, '不定休');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (43, 2, 'モダンイタリアン ベルディソーレ', 'modern-italian-verdisole.jpg', 'モダンな雰囲気で楽しむイタリアンレストラン。', '2000円', '8000円', '464-0814', '愛知県名古屋市千種区今池7-1-3', '12:00', '22:30', 25, '月曜日');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (44, 4, '中華バル 春龍閣', 'chinese-bar-shunryukaku.jpg', 'リーズナブルな価格で本格的な中華が楽しめるバル。', '900円', '3000円', '460-0034', '愛知県名古屋市中区新栄1-2-6', '17:00', '23:00', 30, '不定休');
INSERT IGNORE INTO restaurants (id, category_type, name, image, description, lowest_price, highest_price, postal_code, address, opening_time, closing_time, seating_capacity, holiday) VALUES (45, 19, '海鮮丼専門店 丼太郎', 'kaisendon-senmonten-dontaro.jpg', '新鮮な海の幸がたっぷり盛られた海鮮丼が楽しめる。', '1500円', '5000円', '461-0028', '愛知県名古屋市東区大曽根1-1-9', '11:00', '21:30', 25, '不定休');

-- categoriesテーブル --
INSERT IGNORE INTO categories (id, name) VALUES (1, '和食');
INSERT IGNORE INTO categories (id, name) VALUES (2, 'イタリアン');
INSERT IGNORE INTO categories (id, name) VALUES (3, 'フレンチ');
INSERT IGNORE INTO categories (id, name) VALUES (4, '中華料理');
INSERT IGNORE INTO categories (id, name) VALUES (5, 'アメリカン');
INSERT IGNORE INTO categories (id, name) VALUES (6, 'メキシコ料理');
INSERT IGNORE INTO categories (id, name) VALUES (7, 'インド料理');
INSERT IGNORE INTO categories (id, name) VALUES (8, 'タイ料理');
INSERT IGNORE INTO categories (id, name) VALUES (9, '韓国料理');
INSERT IGNORE INTO categories (id, name) VALUES (10, 'ベトナム料理');
INSERT IGNORE INTO categories (id, name) VALUES (11, 'ベーカリー・カフェ');
INSERT IGNORE INTO categories (id, name) VALUES (12, '居酒屋');
INSERT IGNORE INTO categories (id, name) VALUES (13, '寿司屋');
INSERT IGNORE INTO categories (id, name) VALUES (14, 'ラーメン屋');
INSERT IGNORE INTO categories (id, name) VALUES (15, 'ファーストフード');
INSERT IGNORE INTO categories (id, name) VALUES (16, 'ステーキハウス');
INSERT IGNORE INTO categories (id, name) VALUES (17, 'ベジタリアン／ビーガン');
INSERT IGNORE INTO categories (id, name) VALUES (18, 'デザート・スイーツ');
INSERT IGNORE INTO categories (id, name) VALUES (19, '海鮮レストラン');
INSERT IGNORE INTO categories (id, name) VALUES (20, '焼肉');

-- rolesテーブル --
INSERT IGNORE INTO roles (id, name) VALUES (1, 'ROLE_FREE_MEMBER');
INSERT IGNORE INTO roles (id, name) VALUES (2, 'ROLE_PAID_MEMBER');
INSERT IGNORE INTO roles (id, name) VALUES (3, 'ROLE_ADMIN');

-- membersテーブル --
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (1, '山田 太郎', 'ヤマダ タロウ', '101-0022', '東京都千代田区神田練塀町300番地', '090-1234-5678', 1);
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (2, '山田 次郎', 'ヤマダ ジロウ', '105-0004', '東京都港区芝浦3-4-1', '080-2345-6789', 2);
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (3, '山田 三子', 'ヤマダ サンコ', '150-0042', '東京都渋谷区宇田川町1-8-1', '070-3456-7890', 3);
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (4, '山田 四郎', 'ヤマダ シロウ', '160-0022', '東京都新宿区西新宿2-8-1', '080-4567-8901', 2);
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (5, '山田 五子', 'ヤマダ ゴコ', '170-0012', '東京都豊島区南大塚3-15-1', '090-5678-9012', 2);
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (6, '山田 六郎', 'ヤマダ ロクロウ', '180-0032', '東京都台東区浅草2-3-1', '070-6789-0123', 1);
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (7, '山田 七子', 'ヤマダ ナナコ', '190-0024', '東京都中野区中野5-52-15', '080-7890-1234', 1);
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (8, '山田 八郎', 'ヤマダ ハチロウ', '200-0031', '東京都八王子市元本郷町4-3', '090-8901-2345', 2);
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (9, '山田 九子', 'ヤマダ クコ', '210-0011', '東京都武蔵野市吉祥寺南町1-1', '070-9012-3456', 2);
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (10, '山田 十郎', 'ヤマダ ジュウロウ', '220-0045', '東京都多摩市落合1-1-1', '080-1234-5678', 1);
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (11, '山田 十一子', 'ヤマダ ジュウイチコ', '230-0053', '東京都府中市宮西町1-2', '090-2345-6789', 2);
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (12, '山田 十二郎', 'ヤマダ ジュウニロウ', '240-0032', '東京都立川市柴崎町2-3', '070-3456-7890', 1);
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (13, '山田 十三子', 'ヤマダ ジュウサンコ', '250-0011', '東京都町田市原町田6-1-1', '080-4567-8901', 1);
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (14, '山田 十四子', 'ヤマダ ジュウシコ', '260-0041', '東京都国分寺市本町4-5', '090-5678-9012', 2);
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (15, '山田 十五郎', 'ヤマダ ジュウゴロウ', '270-0052', '東京都八王子市中野上町2-1', '070-6789-0123', 2);
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (16, '山田 十六子', 'ヤマダ ジュウロクコ', '280-0031', '東京都日野市日野台1-1', '080-7890-1234', 1);
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (17, '山田 十七郎', 'ヤマダ ジュウシチロウ', '290-0052', '東京都西東京市ひばりが丘3-1', '090-8901-2345', 2);
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (18, '山田 十八郎', 'ヤマダ ジュウハチロウ', '300-0013', '東京都練馬区早宮1-1', '070-9012-3456', 2);
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (19, '山田 十九子', 'ヤマダ ジュウキュウコ', '310-0022', '東京都江東区豊洲6-1', '080-1234-5678', 1);
INSERT IGNORE INTO members (id, name, furigana, postal_code, address, phone_number, role_id) VALUES (20, '山田 二十子', 'ヤマダ ニジュウコ', '320-0034', '東京都品川区上大崎4-10-2', '090-2345-6789', 2);

-- 認証用テーブル --
INSERT IGNORE INTO authentications (id, email, password) VALUES (1, 'taro@example.com', '578458\@29');
INSERT IGNORE INTO authentications (id, email, password) VALUES (2, 'jiro@example.com', '@d77am90');
INSERT IGNORE INTO authentications (id, email, password) VALUES (3, 'saburo@example.com', '10a!83t29');
INSERT IGNORE INTO authentications (id, email, password) VALUES (4, 'shiro@example.com', 'password');
INSERT IGNORE INTO authentications (id, email, password) VALUES (5, 'goro@example.com', 'password');
INSERT IGNORE INTO authentications (id, email, password) VALUES (6, 'roku@example.com', 'password');
INSERT IGNORE INTO authentications (id, email, password) VALUES (7, 'shichi@example.com', 'password');
INSERT IGNORE INTO authentications (id, email, password) VALUES (8, 'hachi@example.com', 'password');
INSERT IGNORE INTO authentications (id, email, password) VALUES (9, 'kyu@example.com', 'password');
INSERT IGNORE INTO authentications (id, email, password) VALUES (10, 'ju@example.com', 'password');
INSERT IGNORE INTO authentications (id, email, password) VALUES (11, 'juichi@example.com', 'password');
INSERT IGNORE INTO authentications (id, email, password) VALUES (12, 'juniro@example.com', 'password');
INSERT IGNORE INTO authentications (id, email, password) VALUES (13, 'jusan@example.com', 'password');
INSERT IGNORE INTO authentications (id, email, password) VALUES (14, 'jushi@example.com', 'password');
INSERT IGNORE INTO authentications (id, email, password) VALUES (15, 'jugo@example.com', 'password');
INSERT IGNORE INTO authentications (id, email, password) VALUES (16, 'juroku@example.com', 'password');
INSERT IGNORE INTO authentications (id, email, password) VALUES (17, 'jushichi@example.com', 'password');
INSERT IGNORE INTO authentications (id, email, password) VALUES (18, 'juhachi@example.com', 'password');
INSERT IGNORE INTO authentications (id, email, password) VALUES (19, 'juukyu@example.com', 'password');
INSERT IGNORE INTO authentications (id, email, password) VALUES (20, 'nijuu@example.com', 'password');

